routes:
  /en/rss/:
    template: feed/en
    content_type: text/xml
  /pt/rss/:
    template: feed/pt
    content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
